JD-583: add party search
rbkmoney/analytics-proto pull request #12
Opened 2021-08-09 13:22 UTC by vitaxa

2021-08-09 14:43 UTC, PospolitaNV requested changes
LGTM

2021-08-09 14:43 UTC, PospolitaNV commented on proto/search.thrift
> +    1: optional string name
точно name называется?

2021-08-09 14:43 UTC, PospolitaNV commented on proto/search.thrift
> +    list<PartyId> findPartyIds(1: PartyFilterRequest request)
Не уверен в таком методе, но думаю не страшно, потом, когда саппорты начнут пользоваться и осознают юзкейсы - поправим)

2021-08-09 14:46 UTC, vitaxa commented on proto/search.thrift
> +    1: optional string name
Ага, прям так)

2021-08-09 14:47 UTC, vitaxa commented on proto/search.thrift
> +    list<PartyId> findPartyIds(1: PartyFilterRequest request)
Ну да, потом будет не проблема докрутить.

2021-08-10 08:46 UTC, PospolitaNV approved these changes

2021-08-10 08:47 UTC, merged